language: python

python:
  - "3.5"

install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install mongomock
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - py.test

after_success:
  - coveralls